package es.joshluq.pluginkit.buildlogic

import org.gradle.api.Plugin
import org.gradle.api.Project
import org.gradle.api.publish.PublishingExtension
import org.gradle.api.publish.maven.MavenPublication
import org.gradle.kotlin.dsl.configure
import org.gradle.kotlin.dsl.create
import java.net.URI
import java.util.Properties

@Suppress("unused")
class AndroidPublishingConventionPlugin : Plugin<Project> {
    override fun apply(target: Project) {
        with(target) {
            pluginManager.apply("maven-publish")

            afterEvaluate {
                extensions.configure<PublishingExtension> {
                    publications {
                        create<MavenPublication>("release") {
                            // Try to get the "release" component generated by the Android Library plugin
                            val releaseComponent = components.findByName("release")
                            if (releaseComponent != null) {
                                from(releaseComponent)
                            } else {
                                println("AndroidPublishingConventionPlugin: 'release' component not found. Make sure to apply this plugin in an Android Library module.")
                            }

                            groupId = project.group.toString()
                            artifactId = project.name
                            version = getLibraryVersion(project)

                            pom {
                                name.set(project.name)
                                description.set("Android library published automatically")
                            }
                        }
                    }

                    repositories {
                        maven {
                            name = "NexusOnPremise"
                            url = getNexusUrl()
                            isAllowInsecureProtocol = true

                            credentials {
                                username = getNexusUser(project)
                                password = getNexusPassword(project)
                            }
                        }
                    }
                }
            }
        }
    }

    private fun getNexusUrl(): URI {
        val envUrl = System.getenv("NEXUS_URL")
        return if (!envUrl.isNullOrEmpty()) {
            println("Publisher: Using environment URL (CI): $envUrl")
            URI.create(envUrl)
        } else {
            println("Publisher: Using default local URL")
            URI.create("http://localhost:8081/repository/android-releases/")
        }
    }

    private fun getLibraryVersion(project: Project): String {
        val libraryVersion = project.findProperty("libraryVersion") as? String
        return if (!libraryVersion.isNullOrEmpty()) {
            println("Publisher: Using injected version: $libraryVersion")
            libraryVersion
        } else {
            println("Publisher: Using project version: ${project.version}")
            project.version.toString()
        }
    }

    private fun getNexusUser(project: Project): String {
        return System.getenv("NEXUS_USER")
            ?: getLocalProperty("nexusUser", project)
            ?: "admin"
    }

    private fun getNexusPassword(project: Project): String? {
        return System.getenv("NEXUS_PASSWORD")
            ?: getLocalProperty("nexusPassword", project)
    }

    private fun getLocalProperty(key: String, project: Project): String? {
        val propertiesFile = project.rootProject.file("local.properties")
        if (propertiesFile.exists()) {
            val properties = Properties()
            properties.load(propertiesFile.inputStream())
            return properties.getProperty(key)
        }
        return null
    }
}
