[versions]
agp = "9.2.1"
kotlin = "2.3.21"
coreKtx = "1.18.0"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
lifecycleRuntimeKtx = "2.10.0"
activityCompose = "1.13.0"
composeBom = "2026.05.01"
mockk = "1.14.9"
jetbrainsKotlinJvm = "2.3.21"
hilt = "2.59.2"
work = "2.11.2"
hiltWork = "1.3.0"
hiltNavigationCompose = "1.3.0"
retrofit = "3.0.0"
spotless = "8.5.1"
detektVersion = "1.23.8"
okhttp = "5.3.2"
navigationCompose = "2.9.8"
kotlinxSerialization = "1.11.0"
kotlinxCoroutines = "1.11.0"
jackson = "2.21.3"
ksp = "2.3.4"
pluginVersion = "1.5.0-SNAPSHOT"
kitVersion = "1.1.0"
tink = "1.21.0"
datastore = "1.2.1"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-compose-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }

mockk = { group = "io.mockk", name = "mockk", version.ref = "mockk" }
mockk-android = { group = "io.mockk", name = "mockk-android", version.ref = "mockk" }

androidx-material-icons-extended = { group = "androidx.compose.material", name = "material-icons-extended" }
hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "hilt" }
hilt-navigation-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "hiltNavigationCompose" }
retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
retrofit-converter-jackson = { group = "com.squareup.retrofit2", name = "converter-jackson", version.ref = "retrofit" }
okhttp = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttp" }
okhttp-logging-interceptor = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "okhttp" }
androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigationCompose" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinxSerialization" }
kotlinx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "kotlinxCoroutines" }
kotlinx-coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "kotlinxCoroutines" }
kotlinx-coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "kotlinxCoroutines" }
jackson-module-kotlin = { group = "com.fasterxml.jackson.module", name = "jackson-module-kotlin", version.ref = "jackson" }
detekt-formatting = { group = "io.gitlab.arturbosch.detekt", name = "detekt-formatting",  version.ref = "detektVersion" }

androidx-work-runtime = { group = "androidx.work", name = "work-runtime-ktx", version.ref = "work" }
androidx-work-testing = { group = "androidx.work", name = "work-testing", version.ref = "work" }
androidx-hilt-work = { group = "androidx.hilt", name = "hilt-work", version.ref = "hiltWork" }
hilt-compiler-androidx = { group = "androidx.hilt", name = "hilt-compiler", version.ref = "hiltWork" }

fundationkit = { group = "es.joshluq.kit", name = "foundationkit",  version.ref = "kitVersion" }
analitycskit = { group = "es.joshluq.kit", name = "analitycskit",  version.ref = "kitVersion" }
monitorkit = { group = "es.joshluq.kit", name = "monitorkit",  version.ref = "kitVersion" }
androidx-datastore-preferences = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "datastore" }
tink-android = { group = "com.google.crypto.tink", name = "tink-android", version.ref = "tink" }


[bundles]
compose = [
    "androidx-activity-compose",
    "androidx-compose-ui",
    "androidx-compose-ui-graphics",
    "androidx-compose-ui-tooling-preview",
    "androidx-compose-material3"
]
testing-unit = [
    "junit",
    "mockk",
    "kotlinx-coroutines-test"
]
testing-android = [
    "androidx-junit",
    "androidx-espresso-core",
    "mockk-android",
    "androidx-compose-ui-test-junit4",
    "kotlinx-coroutines-test"
]
network = [
    "retrofit",
    "retrofit-converter-jackson",
    "okhttp",
    "okhttp-logging-interceptor"
]
coroutines = [
    "kotlinx-coroutines-core",
    "kotlinx-coroutines-android"
]
navigation = [
    "androidx-navigation-compose",
    "hilt-navigation-compose",
    "kotlinx-serialization-json"
]
kit = [
    "fundationkit",
    "analitycskit",
    "monitorkit"
]
work = [
    "androidx-work-runtime",
    "androidx-hilt-work"
]

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
jetbrains-kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "jetbrainsKotlinJvm" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detektVersion" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }

pluginkit-android-application = { id = "pluginkit.android.application", version.ref = "pluginVersion"}
pluginkit-android-compose = { id = "pluginkit.android.compose", version.ref = "pluginVersion" }
pluginkit-android-library = { id = "pluginkit.android.library", version.ref = "pluginVersion" }
pluginkit-jvm-library = { id = "pluginkit.jvm.library", version.ref = "pluginVersion" }
pluginkit-quality = { id = "pluginkit.quality", version.ref = "pluginVersion" }
pluginkit-android-testing = { id = "pluginkit.android.testing", version.ref = "pluginVersion" }
pluginkit-android-network = { id = "pluginkit.android.network", version.ref = "pluginVersion" }
pluginkit-coroutines = { id = "pluginkit.coroutines", version.ref = "pluginVersion" }
pluginkit-android-hilt = { id = "pluginkit.android.hilt", version.ref = "pluginVersion" }
pluginkit-android-navigation = { id = "pluginkit.android.navigation", version.ref = "pluginVersion" }
pluginkit-formatting = { id = "pluginkit.formatting", version.ref = "pluginVersion" }
pluginkit-android-feature = { id = "pluginkit.android.feature", version.ref = "pluginVersion" }
pluginkit-android-publishing = { id = "pluginkit.android.publishing", version.ref = "pluginVersion" }
pluginkit-android-work = { id = "pluginkit.android.work", version.ref = "pluginVersion" }